// DUNAZOE OS — DOUBLE-ENTRY LEDGER ENGINE
const{Pool}=require("pg");const crypto=require("crypto");
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const ACCOUNTS={WALLET_NGN:{code:"1001",type:"asset"},WALLET_USD:{code:"1002",type:"asset"},THRIFT_SAVINGS:{code:"1003",type:"asset"},ESCROW_HELD:{code:"1004",type:"asset"},VENDOR_WALLET:{code:"1005",type:"asset"},CUSTOMER_PAYABLE:{code:"2001",type:"liability"},VENDOR_PAYABLE:{code:"2002",type:"liability"},REFUND_PAYABLE:{code:"2003",type:"liability"},LOAN_PAYABLE:{code:"2004",type:"liability"},PLATFORM_FEE_REVENUE:{code:"4001",type:"revenue"},THRIFT_CHARGE_REVENUE:{code:"4002",type:"revenue"},DELIVERY_COMM_REVENUE:{code:"4003",type:"revenue"},AI_FEE_REVENUE:{code:"4004",type:"revenue"},INTEREST_REVENUE:{code:"4005",type:"revenue"},GATEWAY_FEE_EXPENSE:{code:"5001",type:"expense"},PAYOUT_EXPENSE:{code:"5002",type:"expense"}};

async function post(entry){const{idempotency_key,description,reference_type,reference_id,lines,correlation_id,posted_by}=entry;
const existing=await pool.query("SELECT * FROM journal_entries WHERE idempotency_key=$1",[idempotency_key]);
if(existing.rows.length>0)return{success:true,entry_id:existing.rows[0].id,duplicate:true};
const total_debits=lines.filter(l=>l.side==="debit").reduce((s,l)=>s+parseFloat(l.amount),0);
const total_credits=lines.filter(l=>l.side==="credit").reduce((s,l)=>s+parseFloat(l.amount),0);
if(Math.abs(total_debits-total_credits)>0.001)throw new Error(`[Ledger] IMBALANCED: debits=${total_debits.toFixed(4)} credits=${total_credits.toFixed(4)}`);
const client=await pool.connect();
try{await client.query("BEGIN");
const je=await client.query("INSERT INTO journal_entries(correlation_id,idempotency_key,description,reference_type,reference_id,posted_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[correlation_id||crypto.randomBytes(8).toString("hex"),idempotency_key,description,reference_type||null,reference_id||null,posted_by||null]);
const entry_id=je.rows[0].id;
for(const line of lines)await client.query("INSERT INTO journal_lines(entry_id,account_code,user_id,side,amount,currency) VALUES($1,$2,$3,$4,$5,$6)",[entry_id,line.account_code,line.user_id||null,line.side,parseFloat(line.amount),line.currency||"NGN"]);
await client.query("COMMIT");return{success:true,entry_id,duplicate:false};}
catch(err){await client.query("ROLLBACK");throw err;}finally{client.release();}}

async function getBalance(account_code,user_id=null,currency="NGN"){const params=[account_code,currency];let where="l.account_code=$1 AND l.currency=$2";if(user_id){where+=` AND l.user_id=$3`;params.push(user_id);}const result=await pool.query(`SELECT COALESCE(SUM(CASE WHEN l.side='credit' THEN l.amount ELSE 0 END),0)-COALESCE(SUM(CASE WHEN l.side='debit' THEN l.amount ELSE 0 END),0) AS balance FROM journal_lines l WHERE ${where}`,params);return parseFloat(result.rows[0].balance||0);}

async function trialBalance(){const result=await pool.query("SELECT l.account_code,a.name,a.type,l.currency,SUM(CASE WHEN l.side='credit' THEN l.amount ELSE 0 END)-SUM(CASE WHEN l.side='debit' THEN l.amount ELSE 0 END) net_balance FROM journal_lines l JOIN journal_entries e ON l.entry_id=e.id JOIN chart_of_accounts a ON l.account_code=a.code GROUP BY l.account_code,a.name,a.type,l.currency ORDER BY l.account_code");const td=result.rows.reduce((s,r)=>s+parseFloat(r.net_balance<0?-r.net_balance:0),0);const tc=result.rows.reduce((s,r)=>s+parseFloat(r.net_balance>0?r.net_balance:0),0);return{accounts:result.rows,balanced:Math.abs(td-tc)<0.01,total_debits:td.toFixed(4),total_credits:tc.toFixed(4)};}

const transactions={
orderPayment:async({order_id,customer_id,vendor_id,amount,correlation_id})=>{const cc=parseFloat((amount*0.05).toFixed(2));const vc=parseFloat((amount*0.05).toFixed(2));const vn=parseFloat((amount-vc).toFixed(2));return post({idempotency_key:`ORDER_PAYMENT_${order_id}`,description:`Order payment #${order_id}`,reference_type:"order",reference_id:String(order_id),correlation_id,posted_by:customer_id,lines:[{account_code:"1001",user_id:customer_id,side:"debit",amount:amount+cc,currency:"NGN"},{account_code:"1004",user_id:vendor_id,side:"credit",amount:vn,currency:"NGN"},{account_code:"4001",side:"credit",amount:cc,currency:"NGN"},{account_code:"4001",user_id:vendor_id,side:"credit",amount:vc,currency:"NGN"},{account_code:"2002",user_id:vendor_id,side:"credit",amount:vn,currency:"NGN"}]});},
escrowRelease:async({escrow_id,order_id,vendor_id,amount,correlation_id})=>post({idempotency_key:`ESCROW_RELEASE_${escrow_id}`,description:`Escrow release order #${order_id}`,reference_type:"escrow",reference_id:String(escrow_id),correlation_id,lines:[{account_code:"1004",user_id:vendor_id,side:"debit",amount,currency:"NGN"},{account_code:"1005",user_id:vendor_id,side:"credit",amount,currency:"NGN"}]}),
thriftContribution:async({account_id,user_id,amount,correlation_id})=>post({idempotency_key:`THRIFT_CONTRIB_${account_id}_${Date.now()}`,description:`Thrift contribution #${account_id}`,reference_type:"thrift",reference_id:String(account_id),correlation_id,posted_by:user_id,lines:[{account_code:"1001",user_id,side:"debit",amount,currency:"NGN"},{account_code:"1003",user_id,side:"credit",amount,currency:"NGN"}]}),
loanDisbursement:async({loan_id,user_id,amount,total_contributed,correlation_id})=>{if(parseFloat(amount)>parseFloat(total_contributed))throw new Error(`[Ledger] LOAN REJECTED: ₦${amount} exceeds max ₦${total_contributed}. RULE: max_loan_amount = total_contributed_amount`);return post({idempotency_key:`LOAN_DISBURSE_${loan_id}`,description:`Loan disbursement #${loan_id}`,reference_type:"loan",reference_id:String(loan_id),correlation_id,posted_by:user_id,lines:[{account_code:"2004",user_id,side:"credit",amount,currency:"NGN"},{account_code:"1001",user_id,side:"debit",amount,currency:"NGN"},{account_code:"1001",user_id,side:"credit",amount,currency:"NGN"}]});},
refund:async({order_id,customer_id,amount,correlation_id,posted_by})=>post({idempotency_key:`REFUND_${order_id}`,description:`Refund order #${order_id}`,reference_type:"refund",reference_id:String(order_id),correlation_id,posted_by,lines:[{account_code:"1004",user_id:customer_id,side:"debit",amount,currency:"NGN"},{account_code:"1001",user_id:customer_id,side:"credit",amount,currency:"NGN"}]}),
thriftServiceCharge:async({user_id,base_amount,loan_id,correlation_id,policy_enabled=true})=>{if(!policy_enabled)return{success:true,skipped:true};const charge=parseFloat((base_amount*0.02).toFixed(2));return post({idempotency_key:`THRIFT_CHARGE_${loan_id}`,description:`Thrift service charge 2% on ₦${base_amount}`,reference_type:"thrift_charge",reference_id:String(loan_id),correlation_id,posted_by:user_id,lines:[{account_code:"1003",user_id,side:"debit",amount:charge,currency:"NGN"},{account_code:"4002",side:"credit",amount:charge,currency:"NGN"}]});},
};
module.exports={post,getBalance,trialBalance,transactions,ACCOUNTS};
