// DUNAZOE OS — EVENT BUS (RabbitMQ + DLX + reconnect)
const amqp=require("amqplib");const RABBITMQ_URL=process.env.RABBITMQ_URL||"amqp://guest:guest@localhost:5672";const EXCHANGE_NAME="dunazoe_events";const DLX_NAME="dunazoe_dead_letter";const MAX_RETRIES=5;let connection=null,channel=null,retries=0;
async function connect(){while(retries<MAX_RETRIES){try{connection=await amqp.connect(RABBITMQ_URL);channel=await connection.createChannel();await channel.assertExchange(EXCHANGE_NAME,"topic",{durable:true});await channel.assertExchange(DLX_NAME,"direct",{durable:true});await channel.assertQueue("dunazoe.dead_letters",{durable:true});connection.on("error",async(e)=>{console.error("[EventBus]",e.message);await _reconnect();});connection.on("close",async()=>{await _reconnect();});retries=0;console.log("[EventBus] ✅ Connected");return;}catch(err){retries++;console.error(`[EventBus] Attempt ${retries}/${MAX_RETRIES}:`,err.message);if(retries>=MAX_RETRIES)return;await new Promise(r=>setTimeout(r,5000*retries));}}}
async function publish(eventType,data,opts={}){if(!channel){console.warn(`[EventBus] No channel — ${eventType} not published`);return false;}try{const payload=Buffer.from(JSON.stringify({event:eventType,data,timestamp:new Date().toISOString(),service:process.env.SERVICE_NAME||"unknown"}));channel.publish(EXCHANGE_NAME,eventType,payload,{persistent:true,contentType:"application/json"});return true;}catch(e){console.error("[EventBus] Publish failed:",e.message);return false;}}
async function subscribe(patterns,queueName,handler){if(!channel)return;const arr=Array.isArray(patterns)?patterns:[patterns];const{queue}=await channel.assertQueue(queueName,{durable:true,arguments:{"x-dead-letter-exchange":DLX_NAME,"x-message-ttl":86400000}});for(const p of arr)await channel.bindQueue(queue,EXCHANGE_NAME,p);await channel.prefetch(1);channel.consume(queue,async(msg)=>{if(!msg)return;let parsed;try{parsed=JSON.parse(msg.content.toString());}catch{channel.nack(msg,false,false);return;}try{await handler(parsed.data,parsed.event,parsed);channel.ack(msg);}catch(e){console.error("[EventBus] Handler failed:",e.message);channel.nack(msg,false,!msg.fields.redelivered);}});}
async function _reconnect(){connection=null;channel=null;await new Promise(r=>setTimeout(r,3000));await connect();}
function isConnected(){return channel!==null;}
const EVENTS={ORDER_CREATED:"order.created",ORDER_PAID:"order.paid",ORDER_CANCELLED:"order.cancelled",ORDER_DELIVERED:"order.delivered",DISPUTE_RAISED:"dispute.raised",DISPUTE_RESOLVED:"dispute.resolved",DELIVERY_ASSIGNED:"delivery.assigned",DELIVERY_STAGE:"delivery.stage",PAYMENT_CONFIRMED:"payment.confirmed",VENDOR_APPROVED:"vendor.approved",MILESTONE_REACHED:"milestone.reached",USER_REGISTERED:"user.registered",STOCK_LOW:"inventory.low_stock",FRAUD_FLAGGED:"fraud.flagged"};
module.exports={connect,publish,subscribe,isConnected,EVENTS};
