-- DUNAZOE OS — SCHEMA PHASE 9: SECURITY + RBAC + TOKEN HARDENING
CREATE TABLE IF NOT EXISTS refresh_tokens (jti TEXT PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL, ip TEXT, fingerprint TEXT, is_revoked BOOLEAN DEFAULT FALSE, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_rt_user ON refresh_tokens(user_id);
CREATE TABLE IF NOT EXISTS token_blacklist (jti TEXT PRIMARY KEY, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS roles (id SERIAL PRIMARY KEY, name TEXT UNIQUE NOT NULL, description TEXT, is_system BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS permissions (id SERIAL PRIMARY KEY, resource TEXT NOT NULL, action TEXT NOT NULL, UNIQUE(resource, action));
CREATE TABLE IF NOT EXISTS role_permissions (role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE, permission_id INTEGER REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS payment_verifications (id SERIAL PRIMARY KEY, order_id INTEGER REFERENCES orders(id), reference TEXT NOT NULL, provider TEXT, expected_amount NUMERIC(12,2), actual_amount NUMERIC(12,2), is_valid BOOLEAN DEFAULT FALSE, failure_reason TEXT, verified_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS escrow_transitions (id SERIAL PRIMARY KEY, escrow_id INTEGER REFERENCES escrow(id), from_status TEXT NOT NULL, to_status TEXT NOT NULL, triggered_by INTEGER REFERENCES users(id), reason TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS financial_audit (id SERIAL PRIMARY KEY, event_type TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id INTEGER, actor_id INTEGER REFERENCES users(id), amount NUMERIC(12,2), currency TEXT DEFAULT 'NGN', detail JSONB, ip TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS delivery_zones (id SERIAL PRIMARY KEY, name TEXT NOT NULL, zone_code TEXT UNIQUE, state TEXT, cities TEXT[], is_active BOOLEAN DEFAULT TRUE);
INSERT INTO roles(name,description,is_system) VALUES ('super_admin','CEO — full access',TRUE),('cto','Chief Technology Officer',TRUE),('head_of_store','Head of Store',TRUE),('head_of_vendors','Head of Vendors',TRUE),('head_of_logistics','Head of Logistics',TRUE),('head_of_marketing','Head of Marketing',TRUE),('cybersecurity_officer','Cybersecurity Officer',TRUE),('regional_coordinator','Regional Coordinator',TRUE),('vendor','Vendor',FALSE),('copytrader','Copy Trader',FALSE),('customer','Customer',FALSE),('delivery_agent','Delivery Agent',FALSE) ON CONFLICT(name) DO NOTHING;
