const crypto=require("crypto");const jwt=require("jsonwebtoken");
const JWT_SECRET=process.env.JWT_SECRET||"dunazoe_secret_change";
const REFRESH_SECRET=process.env.REFRESH_SECRET||"dunazoe_refresh_change";
let pg_pool=null,redis_client=null;
function init(pool){pg_pool=pool;try{const{createClient}=require("redis");redis_client=createClient({url:process.env.REDIS_URL||"redis://localhost:6379"});redis_client.on("error",()=>{});redis_client.connect().catch(()=>{});}catch(_){}}
function getFingerprint(req){return crypto.createHash("sha256").update(`${req.headers["user-agent"]||""}|${req.headers["accept-language"]||""}`).digest("hex").substring(0,16);}
async function issueTokenPair(user_id,role,req){const fp=req?getFingerprint(req):"no-fp";const jti=crypto.randomBytes(16).toString("hex");const access_token=jwt.sign({id:user_id,role,jti,fp},JWT_SECRET,{expiresIn:"15m"});const refresh_jti=crypto.randomBytes(16).toString("hex");const refresh_token=jwt.sign({id:user_id,role,jti:refresh_jti,type:"refresh"},REFRESH_SECRET,{expiresIn:"30d"});if(pg_pool){const exp=new Date(Date.now()+30*24*3600*1000);await pg_pool.query("INSERT INTO refresh_tokens(jti,user_id,token_hash,ip,fingerprint,expires_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(jti) DO NOTHING",[refresh_jti,user_id,crypto.createHash("sha256").update(refresh_token).digest("hex"),req?.ip||"0.0.0.0",fp,exp]).catch(()=>{});}return{access_token,refresh_token,expires_in:900};}
async function blacklistToken(token){try{const d=jwt.decode(token);if(!d?.jti||!d?.exp)return;const ttl=d.exp-Math.floor(Date.now()/1000);if(ttl<=0)return;if(redis_client?.isReady)await redis_client.set(`blacklist:${d.jti}`,"1",{EX:ttl});else if(pg_pool)await pg_pool.query("INSERT INTO token_blacklist(jti,expires_at) VALUES($1,to_timestamp($2)) ON CONFLICT DO NOTHING",[d.jti,d.exp]).catch(()=>{});}catch(_){}}
async function verifyAccessToken(token){let d;try{d=jwt.verify(token,JWT_SECRET);}catch(e){return{valid:false,error:e.message};}if(d.jti){if(redis_client?.isReady){const bl=await redis_client.exists(`blacklist:${d.jti}`);if(bl)return{valid:false,error:"Token revoked"};}else if(pg_pool){const bl=await pg_pool.query("SELECT jti FROM token_blacklist WHERE jti=$1 AND expires_at>NOW()",[d.jti]).catch(()=>({rows:[]}));if(bl.rows.length)return{valid:false,error:"Token revoked"};}}return{valid:true,user:{id:d.id,role:d.role,jti:d.jti}};}
async function logout(access_token,user_id){await blacklistToken(access_token);if(pg_pool)await pg_pool.query("UPDATE refresh_tokens SET is_revoked=TRUE WHERE user_id=$1",[user_id]).catch(()=>{});}
function verifyPaymentAmount(expected,actual){const e=Math.round(parseFloat(expected)*100),a=Math.round(parseFloat(actual)*100);if(e!==a)return{valid:false,error:`Amount mismatch: expected ₦${(e/100).toFixed(2)}, got ₦${(a/100).toFixed(2)}`};return{valid:true};}
const ESCROW_TRANSITIONS={pending:["paid"],paid:["locked","released"],locked:["released","refunded"],released:[],refunded:[]};
function validateEscrowTransition(from,to,dispute_exists=false){if(!(ESCROW_TRANSITIONS[from]||[]).includes(to))return{valid:false,error:`Invalid escrow transition: ${from} → ${to}`};if(to==="released"&&dispute_exists)return{valid:false,error:"Cannot release escrow while dispute is open"};return{valid:true};}
function requireAuth(){return async(req,res,next)=>{const token=(req.headers["authorization"]||"").replace("Bearer ","").trim();if(!token)return res.status(401).json({success:false,error:"No token provided"});const result=await verifyAccessToken(token);if(!result.valid)return res.status(401).json({success:false,error:result.error});req.user=result.user;req.user_id=result.user.id;next();};}
function requireRole(...roles){const allowed=roles.flat();return(req,res,next)=>{if(!req.user)return res.status(401).json({success:false,error:"Unauthorised"});if(!allowed.includes(req.user.role))return res.status(403).json({success:false,error:`Access denied. Required: ${allowed.join(" or ")}`});next();};}
module.exports={init,issueTokenPair,blacklistToken,verifyAccessToken,logout,verifyPaymentAmount,validateEscrowTransition,requireAuth,requireRole,getFingerprint};
