// DUNAZOE OS — SERVICE CLIENT v2 (HMAC signed + retry + trace)
const axios=require("axios");const crypto=require("crypto");
const INTERNAL_SECRET=process.env.INTERNAL_SECRET||"dunazoe_internal_change";
const SERVICE_NAME=process.env.SERVICE_NAME||"dunazoe-service";
const DEFAULT_TIMEOUT=parseInt(process.env.SVC_TIMEOUT_MS||"8000");
const MAX_RETRIES=parseInt(process.env.SVC_MAX_RETRIES||"2");
const SERVICES={auth:"http://localhost:4001",user:"http://localhost:4002",vendor:"http://localhost:4003",product:"http://localhost:4004",inventory:"http://localhost:4005",order:"http://localhost:4006",escrow:"http://localhost:4007",fraud:"http://localhost:4008",wallet:"http://localhost:4009",thrift:"http://localhost:4010",trust:"http://localhost:4011",loan:"http://localhost:4012",commission:"http://localhost:4013",ai:"http://localhost:4014",payment:"http://localhost:4015",dispute:"http://localhost:4016",notification:"http://localhost:4017",logistics:"http://localhost:4018",flags:"http://localhost:4019",upload:"http://localhost:4020",realtime:"http://localhost:4021",search:"http://localhost:4022",kyc:"http://localhost:4023",reconciliation:"http://localhost:4024",reliability:"http://localhost:4025"};
Object.keys(SERVICES).forEach(k=>{const envKey=`${k.toUpperCase().replace(/-/g,"_")}_SERVICE_URL`;if(process.env[envKey])SERVICES[k]=process.env[envKey];});
function signRequest(method,path,body={}){const timestamp=Math.floor(Date.now()/1000).toString();const nonce=crypto.randomBytes(8).toString("hex");const body_hash=crypto.createHash("sha256").update(JSON.stringify(body)).digest("hex");const payload=`${method.toUpperCase()}\n${path}\n${timestamp}\n${nonce}\n${body_hash}`;const signature=crypto.createHmac("sha256",INTERNAL_SECRET).update(payload).digest("hex");return{"x-service-name":SERVICE_NAME,"x-signature":signature,"x-timestamp":timestamp,"x-nonce":nonce,"Content-Type":"application/json"};}
async function call(service,method,path,body={},opts={}){const base=SERVICES[service];if(!base)throw new Error(`Unknown service: "${service}"`);const timeout=opts.timeout||DEFAULT_TIMEOUT;const retries=opts.retries!==undefined?opts.retries:MAX_RETRIES;const trace_id=opts.trace_id||crypto.randomBytes(8).toString("hex");const headers={...signRequest(method,path,body),"x-trace-id":trace_id};let last_error;for(let i=0;i<=retries;i++){try{const res=await axios.request({method,url:`${base}${path}`,headers,timeout,data:["post","put","patch"].includes(method.toLowerCase())?body:undefined,params:method.toLowerCase()==="get"?body:undefined});return res.data;}catch(err){last_error=err;const status=err.response?.status;if(status&&status>=400&&status<500){const e=new Error(err.response?.data?.error||err.message);e.status=status;e.service=service;e.response=err.response?.data;throw e;}if(i<retries)await new Promise(r=>setTimeout(r,Math.min(1000*Math.pow(2,i),8000)));}}const e=new Error(last_error?.response?.data?.error||last_error?.message||`${service} unavailable`);e.status=last_error?.response?.status||503;e.service=service;throw e;}
const svc={get:(s,p,b,o)=>call(s,"get",p,b,o),post:(s,p,b,o)=>call(s,"post",p,b,o),put:(s,p,b,o)=>call(s,"put",p,b,o),delete:(s,p,o)=>call(s,"delete",p,{},o),patch:(s,p,b,o)=>call(s,"patch",p,b,o),emit:async(uid,event,data)=>{try{await call("realtime","post",`/emit/user/${uid}`,{event,data},{retries:0,timeout:1000});}catch(_){}},emitOrder:async(oid,event,data)=>{try{await call("realtime","post",`/emit/order/${oid}`,{event,data},{retries:0,timeout:1000});}catch(_){}},notify:async(uid,title,body,channels=["in_app"])=>{try{await call("notification","post","/notifications/send",{user_id:uid,title,body,channels},{retries:1});}catch(_){}},isEnabled:async(flag)=>{try{const r=await call("flags","get",`/flags/${flag}`,{},{retries:0,timeout:1000});return r?.enabled!==false;}catch(_){return true;}},SERVICES};
module.exports=svc;
