// DUNAZOE OS — TRANSACTIONAL OUTBOX WORKER
const{Pool}=require("pg");const amqp=require("amqplib");const crypto=require("crypto");
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const RABBITMQ_URL=process.env.RABBITMQ_URL||"amqp://guest:guest@localhost:5672";const EXCHANGE_NAME="dunazoe_events";const POLL_INTERVAL=parseInt(process.env.OUTBOX_POLL_MS||"5000");const MAX_ATTEMPTS=parseInt(process.env.OUTBOX_MAX_ATTEMPTS||"10");
let channel=null,worker_running=false;
async function writeEvent(client_or_pool,event){const{event_type,aggregate_type,aggregate_id,payload,correlation_id}=event;const event_id=crypto.randomBytes(16).toString("hex");await client_or_pool.query("INSERT INTO outbox_events(event_id,event_type,aggregate_type,aggregate_id,payload,correlation_id) VALUES($1,$2,$3,$4,$5,$6)",[event_id,event_type,aggregate_type,String(aggregate_id),JSON.stringify(payload),correlation_id||null]);return event_id;}
async function connectRabbitMQ(){try{const conn=await amqp.connect(RABBITMQ_URL);channel=await conn.createChannel();await channel.assertExchange(EXCHANGE_NAME,"topic",{durable:true});await channel.assertExchange("dunazoe_dead_letter","direct",{durable:true});conn.on("error",async()=>{channel=null;setTimeout(connectRabbitMQ,5000);});conn.on("close",async()=>{channel=null;setTimeout(connectRabbitMQ,5000);});console.log("[Outbox] RabbitMQ connected ✓");}catch(e){console.error("[Outbox] RabbitMQ failed:",e.message);setTimeout(connectRabbitMQ,5000);}}
async function processOutbox(){const client=await pool.connect();try{await client.query("BEGIN");const events=await client.query("SELECT * FROM outbox_events WHERE status='pending' AND next_attempt_at<=NOW() ORDER BY created_at ASC LIMIT 20 FOR UPDATE SKIP LOCKED");for(const event of events.rows){try{if(!channel)throw new Error("No RabbitMQ channel");const message=Buffer.from(JSON.stringify({event_id:event.event_id,event_type:event.event_type,aggregate_type:event.aggregate_type,aggregate_id:event.aggregate_id,payload:event.payload,correlation_id:event.correlation_id,timestamp:new Date().toISOString()}));channel.publish(EXCHANGE_NAME,event.event_type,message,{persistent:true,messageId:event.event_id,contentType:"application/json"});await client.query("UPDATE outbox_events SET status='published',published_at=NOW() WHERE id=$1",[event.id]);}catch(err){const attempts=event.attempts+1;const is_dead=attempts>=MAX_ATTEMPTS;const backoff_secs=Math.min(Math.pow(2,attempts)*5,3600);const next_attempt=new Date(Date.now()+backoff_secs*1000);if(is_dead){await client.query("INSERT INTO outbox_dead_letters(event_id,event_type,aggregate_id,payload,error,attempts) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(event_id) DO NOTHING",[event.event_id,event.event_type,event.aggregate_id,event.payload,err.message,attempts]);await client.query("UPDATE outbox_events SET status='dead_letter',attempts=$1,error_message=$2 WHERE id=$3",[attempts,err.message,event.id]);}else{await client.query("UPDATE outbox_events SET attempts=$1,last_attempt_at=NOW(),next_attempt_at=$2,error_message=$3 WHERE id=$4",[attempts,next_attempt,err.message,event.id]);}}}await client.query("COMMIT");return events.rows.length;}catch(err){await client.query("ROLLBACK");console.error("[Outbox]",err.message);return 0;}finally{client.release();}}
async function startWorker(){if(worker_running)return;worker_running=true;await connectRabbitMQ();console.log(`[Outbox] Worker started (poll:${POLL_INTERVAL}ms)`);const run=async()=>{if(!worker_running)return;try{const n=await processOutbox();if(n>0)console.log(`[Outbox] Published ${n} events`);}catch(e){console.error("[Outbox] Worker error:",e.message);}setTimeout(run,POLL_INTERVAL);};run();}
function stopWorker(){worker_running=false;}
async function getStats(){const stats=await pool.query("SELECT status,COUNT(*) count FROM outbox_events WHERE created_at>NOW()-INTERVAL '24 hours' GROUP BY status");const dead=await pool.query("SELECT COUNT(*) c FROM outbox_dead_letters");return{last_24h:Object.fromEntries(stats.rows.map(r=>[r.status,parseInt(r.count)])),total_dead:parseInt(dead.rows[0].c),worker_alive:worker_running};}
module.exports={writeEvent,startWorker,stopWorker,processOutbox,getStats};
